/**
 * Phrase banks for sports humor.
 * Rebalanced: ~30% beer-themed, ~40% witty sports commentary, ~30% general humor/pop culture.
 */

// ─── Beer Transitions (best 18, down from 55) ───────────────────────────────

export const beerTransitions: string[] = [
  'Pour one out for the losing side.',
  'This calls for a celebratory round.',
  "Time to crack open a cold one and let this sink in.",
  "Cheers to that — and by 'that,' we mean everything about this game.",
  "Bartender, make it a double. This game earned it.",
  "That deserves a standing ovation and a fresh pint.",
  "Let's raise a glass to absolute chaos.",
  "Cheers to the beautiful absurdity of sports.",
  "We paused to take a sip. We suggest you do the same.",
  "And just like that, the mood at the bar shifts.",
  "The fridge isn't going to empty itself. Unlike this team's chances.",
  "That play was smoother than a fresh pour on nitro.",
  "We've seen bar fights less intense than this game.",
  "Like a proper stout, this game has layers.",
  "And that, friends, is what we in the business call 'a moment.'",
  "This game pairs well with an amber ale and low expectations.",
  "A toast: to whoever bet the over on this one.",
  "The pub quiz about this game is going to be legendary.",
];

// ─── Non-Beer Transitions (35 entries — witty sports commentary) ─────────────

export const wittyTransitions: string[] = [
  "And just like that, the narrative shifts completely.",
  "Let's take a breath and appreciate what just happened.",
  "The momentum is unmistakable at this point.",
  "You could feel the tide turning from a mile away.",
  "Sometimes the scoreboard doesn't tell the whole story. This time, it absolutely does.",
  "That's the kind of moment that defines a season.",
  "You can almost hear the highlight reels being edited in real time.",
  "Nobody is going to forget that sequence anytime soon.",
  "This is what separates good teams from great ones.",
  "The turning point was clear — and it was devastating.",
  "Everything changed after that play, and both sides knew it.",
  "Every once in a while, a game reminds you why you love sports.",
  "That's going straight to the top of the highlights package.",
  "Sometimes the game plan just comes together perfectly.",
  "The energy in the building shifted completely after that.",
  "If you blinked, you missed it. If you didn't blink, you still can't believe it.",
  "There's a thin line between chaos and brilliance. This was both.",
  "We've reached the part of the story where things get interesting.",
  "Just when you thought this game couldn't get wilder...",
  "And that's the kind of play coaches will be showing film of all week.",
  "The balance of power just tipped, and it tipped hard.",
  "That was the moment this went from a game to a statement.",
  "So much for predictions — this game had other plans.",
  "Whoever writes the movie version of this is going to have a hard time making it believable.",
  "And with that, the conversation changes entirely.",
  "Credit where credit is due — that was exceptional.",
  "Some teams talk about wanting it more. This team proved it.",
  "The writing was on the wall, and it was written in bold.",
  "You don't see this level of execution every day.",
  "That was textbook. Literally coaches will put that in a textbook.",
  "At some point, you have to stop being surprised and start being impressed.",
  "The gap between these two teams just became a canyon.",
  "This is the kind of performance that earns respect across the league.",
  "And that's why the pregame predictions are just entertainment.",
  "The storyline here practically writes itself.",
];

// ─── General Humor Transitions (pop culture, everyday wit — no beer) ─────────

export const generalHumorTransitions: string[] = [
  "Somebody check the simulation — this can't be real life.",
  "The internet is going to have a field day with this one.",
  "That's going straight to the group chat.",
  "Somewhere, a fantasy football manager just punched a wall.",
  "You can't make this stuff up. Well, you could, but nobody would believe you.",
  "We'd call this a plot twist, but even Netflix would say it's too much.",
  "That's the kind of thing that breaks Twitter for a solid hour.",
  "If sports were scripted, even the writers would have called this unrealistic.",
  "Somewhere out there, a very smug person is saying 'I told you so.'",
  "This is why we can't have nice predictions.",
  "That's going in the time capsule, no question.",
  "File that one under 'things that actually happened in professional sports.'",
  "Reality continues to be stranger than fiction.",
  "And with that, a thousand hot takes were born.",
  "The memes from this game are going to be legendary.",
  "Somebody owes somebody an apology after that performance.",
  "That's the kind of moment that trends for days.",
  "The sports gods have a peculiar sense of humor today.",
  "If there were a Mount Rushmore of wild sports moments, this would be on it.",
  "We're going to remember where we were when this happened.",
  "That moment just bought real estate in our heads. Rent-free.",
  "Our group chat just exploded, and honestly, fair.",
  "Somebody call the authorities — we just witnessed something extraordinary.",
  "The drama is so thick you could cut it with a knife.",
  "This is why sports are better than any reality TV show ever produced.",
  "We're not sure whether to laugh or cry, so we're doing both.",
  "Absolute scenes. That's the only way to describe it.",
  "The algorithm is going to love this one.",
  "That's a career-defining moment right there.",
  "Everyone watching just became a witness to history.",
];

// ─── Combined Transitions (use this for random selection in articles) ─────────

export const allTransitions: string[] = [
  ...beerTransitions,
  ...wittyTransitions,
  ...generalHumorTransitions,
];

// ─── Witty Commentary (no beer, sharp sports observations) ───────────────────

export const wittyCommentary: string[] = [
  "That's the kind of performance that makes you rethink everything you thought you knew.",
  "Somebody check the simulation settings — this can't be real.",
  "If we're being honest, nobody had this on their prediction list.",
  "The stat sheet reads like fiction, but here we are.",
  "We've officially entered 'you had to see it to believe it' territory.",
  "That's the sort of performance that earns a documentary someday.",
  "There's a fine line between confidence and arrogance. This team walked it perfectly.",
  "You could teach a masterclass on that half alone.",
  "The scouting report just became obsolete.",
  "That's not a performance. That's a statement with an exclamation point.",
  "The word 'dominant' gets thrown around a lot. Today it was earned.",
  "If effort were measured in watts, that team would power a city.",
  "Sometimes a team just has it, and tonight they had all of it.",
  "The analytics crowd and the eye-test crowd can actually agree on this one.",
  "They made it look easy. It was not easy. That's what makes it impressive.",
  "That performance just entered the 'show your grandchildren' category.",
  "Somewhere, a coach is using this footage as the gold standard.",
  "There's playing well, and then there's whatever that was. Levels above.",
  "The kind of game that makes rival fans nervous for the rest of the season.",
  "They didn't just beat the opponent — they set the tone for the entire league.",
  "That's the type of win that changes expectations permanently.",
  "If you could bottle that performance, it would sell out immediately.",
  "This wasn't just a win. It was an announcement.",
  "They played like a team that knows something the rest of us don't.",
  "The game plan was flawless. The execution was better.",
  "Everyone who left early just learned a valuable life lesson.",
  "The gap between these two sides today was not measurable by normal standards.",
  "That was the athletic equivalent of 'I'm not even trying that hard.'",
  "The box score is impressive. The film is going to be even more impressive.",
  "If this team plays like this consistently, cancel the rest of the season.",
  "The composure under pressure was almost inhuman.",
  "You know a performance is special when both fan bases acknowledge it.",
  "That's the kind of game that gets replayed on rainy Sunday afternoons for years.",
  "When people say 'next level,' this is the level they're talking about.",
  "The opposition didn't play badly. They were just outclassed completely.",
];

// ─── Contextual Reactions (matched to game situations) ──────────────────────

export const contextualReactions = {
  dominant: [
    "That wasn't a competition. That was a demonstration.",
    "If mercy rules existed in this sport, we'd have invoked one.",
    "Total domination. Start to finish. No questions asked.",
    "The other team showed up. That's about the nicest thing we can say.",
    "When the post-game handshake is the most competitive part of the match...",
    "Like watching a professional play against amateurs. Respectfully.",
    "They controlled every phase of this game. Every single one.",
    "The kind of win that makes you feel bad for the other side. Almost.",
    "If there's a level above 'complete control,' this team found it.",
    "That was surgical. Cold, calculated, and absolutely ruthless.",
  ],
  comeback: [
    "Written off at halftime. Celebrating at the final whistle.",
    "The greatest trick this team ever pulled was making us count them out.",
    "Down but never out. That should be tattooed somewhere.",
    "They dug a hole, found a shovel, and built a mansion.",
    "From the ashes of that first half, a phoenix emerged. A loud, victorious phoenix.",
    "Someone forgot to tell them they were supposed to lose.",
    "The momentum shift was so violent it should be classified as a weather event.",
    "That second half was a completely different sport.",
    "Resilience isn't a word. It's a lifestyle. And this team lives it.",
    "The script got flipped, torn up, and rewritten in real time.",
  ],
  collapse: [
    "That's the kind of collapse that haunts a franchise for years.",
    "They had it. They really had it. And then they spectacularly didn't.",
    "The wheels didn't just come off — they rolled into traffic.",
    "From comfortable lead to catastrophic implosion in record time.",
    "Someone needs to study the tape and then immediately burn the tape.",
    "That was less of a collapse and more of a controlled demolition.",
    "The lead evaporated faster than enthusiasm at a Monday morning meeting.",
    "They went from cruise control to crisis mode without passing through anything in between.",
    "If there were an award for the most dramatic way to lose a lead, they'd win unanimously.",
    "The only thing more shocking than the result is how quickly it unraveled.",
  ],
  controversial: [
    "That call is going to be debated until the heat death of the universe.",
    "The officials just became the most talked-about people in the sport.",
    "Whether you think it was right or wrong, you definitely have an opinion.",
    "The replay didn't make it any clearer. But it did make everyone angrier.",
    "That decision will be Exhibit A in the 'fix the officiating' argument.",
    "Controversial doesn't begin to cover it. Divisive gets closer.",
    "Both sides have legitimate grievances. The refs have a legitimate headache.",
    "The post-game discourse is going to be louder than the game itself.",
    "If you want to start an argument, just bring up that call.",
    "The technology exists to get these calls right. The willpower, apparently, does not.",
  ],
  historic: [
    "Record broken. History made. Textbooks updated.",
    "That's the kind of record that was supposed to stand for decades.",
    "We just watched something that may never happen again in our lifetimes.",
    "The record books just got a new chapter. Written in bold.",
    "When you witness history, you remember the details. Remember this one.",
    "That record didn't just fall. It was demolished.",
    "Future generations will read about this and think it's exaggerated. It's not.",
    "Some records feel inevitable when they fall. This one felt impossible until it happened.",
    "Add it to the list of things we thought we'd never see.",
    "The milestone was reached, and the moment was perfect.",
  ],
} as const;

// ─── Humor Interjections (55 entries) ───────────────────────────────────────

export const humorInterjections: string[] = [
  "And yes, we checked — that score is real.",
  "No, your eyes aren't deceiving you.",
  "We wish we were making this up.",
  "You can't script this stuff. Seriously, Hollywood would reject it.",
  "(Narrator: It was, in fact, that bad.)",
  "We'll give you a moment to process that.",
  "Read that again. Slowly.",
  "Let that sink in. We'll wait.",
  "For the record, we triple-checked.",
  "Yes, that actually happened. In a professional sport. On purpose.",
  "And no, this isn't satire. Though we understand the confusion.",
  "Believe it or not, this gets weirder.",
  "We're not crying, you're crying. Okay, we're both crying.",
  "Sports, everybody. Sports.",
  "Somewhere, a sports analyst just spit out their coffee.",
  "The spreadsheet nerds are having a field day with this one.",
  "Analytics Twitter is going to explode.",
  "Your fantasy team owners are either thrilled or devastated. No in-between.",
  "There is no in-between with this team.",
  "At this point, we're just along for the ride.",
  "The audacity. The absolute audacity.",
  "Chef's kiss. No notes.",
  "If you turned this game off early, we have bad news about your decision-making.",
  "This is fine. Everything is fine. (It is not fine.)",
  "We'd make a joke, but reality already did that for us.",
  "The memes are writing themselves at this point.",
  "Even the commentators ran out of words for that one.",
  "File this under: Things We Didn't See Coming.",
  "That's going straight to the blooper reel.",
  "Plot twist nobody asked for but everyone deserved.",
  "Okay, but seriously — how?",
  "In today's edition of 'Sports Are Weird'...",
  "We genuinely don't know how to feel about this.",
  "Somebody tell us this is a simulation.",
  "The stat sheet doesn't lie. We kind of wish it did.",
  "Well, that happened. Moving on.",
  "Is it too early to call this game of the year? Asking for a friend.",
  "We've been staring at this box score for five minutes.",
  "That's the kind of stat line that ruins friendships.",
  "The record books just got a new entry.",
  "Alexa, play the sad trombone.",
  "The commentator literally said 'wow' three times. Same.",
  "We've officially entered the 'anything can happen' zone.",
  "If you had this on your bingo card, you're a wizard.",
  "Statistically improbable. Actually happened anyway.",
  "The laws of physics would like a word.",
  "Our collective jaws are on the floor.",
  "That's not even fair. Like, actually unfair.",
  "We need a moment. Or twelve.",
  "This is the kind of game that makes you question everything.",
  "If this were a movie, you'd say it was unrealistic.",
  "The scoreboard operator just looked at the camera like they were on The Office.",
  "Let's all just take a breath here.",
  "We've seen it all now. Actually, no, sports will surprise us again tomorrow.",
  "The universe has a sense of humor, and today it's laughing at us.",
];

// ─── Opening Lines (rebalanced: ~30% beer, ~70% non-beer) ──────────────────

export const openingLines: string[] = [
  // Beer-themed openers (10)
  'Well, sports fans, grab your beverage of choice because this one is a doozy.',
  'Settle in, crack a cold one, and prepare yourself for this.',
  "If you haven't already poured yourself something, now's the time.",
  "Grab a seat. Grab a beer. This is going to be good.",
  "Pull up a barstool — you're going to want to sit down for this.",
  "Welcome back to the only sports coverage that pairs with a cold one.",
  "Clear your schedule and fill your glass — this is a big one.",
  "It's a great day to be a sports fan and a better day to have a fridge nearby.",
  "Today's sports forecast: 100% chance of overreactions and cold beverages.",
  "Wake up, sports fans. We've got something brewing — and we don't just mean the coffee.",

  // Non-beer openers (25)
  "Oh boy. Where do we even begin with this one?",
  "Buckle up, buttercup — this game was something else.",
  "Ladies, gentlemen, and fellow couch warriors — we bring news.",
  "Stop what you're doing. This is worth your full attention.",
  "What a day. What a beautiful, chaotic day in sports.",
  "You know those games you tell your grandkids about? This is one.",
  "We interrupt your regularly scheduled scrolling for something actually interesting.",
  "Another day, another reason to love (and question) sports.",
  "Friends, we gather here today to discuss what just happened in sports.",
  "The sports gods have spoken, and they have chosen violence.",
  "Some games are forgettable. This was not one of them.",
  "Today in sports: drama, heartbreak, and the occasional moment of actual competence.",
  "There are normal games. And then there's whatever this was.",
  "Sports happened today. And they happened HARD.",
  "Alert: This recap contains scenes of athletic excellence and poor refereeing.",
  "Let us set the scene: a packed stadium, two teams, and zero chill.",
  "The scoreboard doesn't lie, and today it's telling quite a story.",
  "Before we get into this, we need you to promise you're sitting down.",
  "Another absolute banger of a game and we are HERE for it.",
  "Good evening, you beautiful degenerates. We have sports to discuss.",
  "Well, that escalated quickly. And by quickly, we mean from the opening whistle.",
  "We've got a lot to unpack here, so let's get straight to it.",
  "If you only read one game recap today, make it this one.",
  "Strap in. This is not the kind of game you can summarize in one sentence.",
  "The pregame predictions aged about as well as milk in the sun.",
];

// ─── Closing Lines (rebalanced: ~30% beer, ~70% non-beer) ──────────────────

export const closingLines: string[] = [
  // Beer-themed closers (10)
  "And on that note, we're heading to the bar. Cheers.",
  "That's all from us. Tip your bartender.",
  "Until next time — stay hydrated. With whatever you prefer.",
  "That's a wrap. We'll be at the pub if you need us.",
  "Game over. The post-game celebrations have officially begun.",
  "Last call for hot takes. First call for cold drinks.",
  "Thanks for joining us. Your tab is still open.",
  "Signing off with a full heart and an empty glass.",
  "End of game. Beginning of happy hour.",
  "That does it for us. May your teams win and your beverages be cold.",

  // Non-beer closers (25)
  "And we're out. Like the losing team's playoff hopes.",
  "Final thoughts: wow. That's it. That's the thought. Wow.",
  "That's it from the best seats in the house — our couches.",
  "Thanks for reading. We're going to go stare at the wall and process this game.",
  "On that note, we're tapping out. Catch you on the flip side.",
  "And scene. The credits roll on another unforgettable game.",
  "That's all the sports we can handle for one day. See you tomorrow.",
  "We're going to stop here before we run out of adjectives.",
  "Until the next time sports make us feel feelings, take care of yourselves.",
  "And with that, we close the book on this one. What a chapter.",
  "That's all, folks. If you need us, we'll be obsessively checking the highlight reel.",
  "The final whistle blew, but the debates are just getting started.",
  "We'll leave you with this: sports are incredible, and today was proof.",
  "Go hug your loved ones. This game took an emotional toll.",
  "If you made it to the end of this recap, you're a real one.",
  "The game is over, but the takes will live forever.",
  "We're done here, but the discourse? The discourse is just beginning.",
  "Stay tuned. If today is any indication, tomorrow is going to be wild too.",
  "That's a wrap on a genuinely remarkable day of sports.",
  "We'd say 'see you next time,' but knowing sports, something wild will happen in about three hours.",
  "Thank you for reading. Now go touch grass — unless there's more games on.",
  "The final buzzer is our cue to exit. What a performance.",
  "Goodnight, and good luck processing everything that just happened.",
  "That's all the chaos we can document for one evening. Stay safe out there.",
  "And that's the ballgame. Genuinely, what a time to be watching sports.",
];

// ─── Sentiment Phrases ──────────────────────────────────────────────────────

export const sentimentPhrases = {
  bigWin: [
    'Absolutely dominant.',
    'That was a statement game.',
    'Total control from start to finish.',
    'This team means business.',
    'A performance for the ages.',
    'Put that one in a frame.',
    "They didn't just win — they made a point.",
    "That's the kind of win that echoes.",
    'Championship-caliber performance right there.',
    'Complete and utter destruction.',
  ],
  closeWin: [
    'Survived by the skin of their teeth.',
    "Ugly? Yes. A win? Also yes. We'll take it.",
    'A win is a win, even if it took ten years off our lives.',
    "Not pretty, but effective. Kind of like parallel parking.",
    "Gritty, gutsy, and they'll take it.",
    "That's called clutch. Or luck. Probably both.",
    'Pulled it out when it mattered most.',
    'They found a way. Barely.',
    "Heart attack football at its finest.",
    "The ugly wins count the same on the standings.",
  ],
  loss: [
    "Rough night. The less said, the better.",
    "That one's going to sting for a while.",
    "Back to the drawing board.",
    "They'll want to forget this one. We won't let them.",
    "A performance that inspires soul-searching.",
    "The only silver lining is that it's over.",
    "If you're a fan of this team, our condolences.",
    "That was... something. Not something good, but something.",
    "They showed up, technically. That's about all we can say.",
    "Time heals all wounds. The off-season is going to feel long.",
  ],
  upset: [
    'Nobody saw this coming!',
    'The underdog has bitten back.',
    "Alert: chaos has entered the chat.",
    "Tear up your brackets. Burn your predictions. Start over.",
    "The sports gods love nothing more than an upset.",
    "David just knocked out Goliath, and the crowd is going mental.",
    "If you bet on this, you're either psychic or insane. Congrats.",
    "The favorites? Humbled. The underdogs? Legendary.",
    "This is why they play the games, folks.",
    "Form goes out the window. Magic walks in.",
  ],
  controversy: [
    "The refs are catching heat, and honestly, they kind of deserve it.",
    "VAR/Review just became the most hated technology since the alarm clock.",
    "That call is going to be debated in living rooms for decades.",
    "Controversial doesn't even begin to cover it.",
    "The internet is a warzone over this one.",
    "We're not going to weigh in on the call. Just kidding — it was awful.",
    "The officiating tonight could generously be described as 'creative.'",
    "That decision will haunt the league office for weeks.",
    "Hot take: the refs need glasses. Cold take: everyone agrees.",
    "If bad calls were currency, the refs would be billionaires.",
  ],
} as const;

// ─── Utility ────────────────────────────────────────────────────────────────

/**
 * Pick a random phrase from an array.
 */
export function randomPhrase(phrases: readonly string[]): string {
  return phrases[Math.floor(Math.random() * phrases.length)]!;
}

/**
 * Pick N unique random phrases from an array.
 */
export function randomPhrases(phrases: readonly string[], count: number): string[] {
  const shuffled = [...phrases].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
