/**
 * Extensive phrase banks for beer-themed sports humor.
 * 200+ entries across categories.
 */

// ─── Beer Transitions (55 entries) ──────────────────────────────────────────

export const beerTransitions: string[] = [
  'Pour one out for the losing side.',
  'This calls for a celebratory round.',
  "Someone get the ref a drink — they're going to need it.",
  "On that note, we're switching to something stronger.",
  "Time to crack open a cold one and let this sink in.",
  "If you're not drinking yet, now's the time to start.",
  "Cheers to that — and by 'that,' we mean everything about this game.",
  "We'll toast to this one later. Right now, we're still in shock.",
  "Bartender, make it a double. This game earned it.",
  "That deserves a standing ovation and a fresh pint.",
  "Let's raise a glass to absolute chaos.",
  "Somewhere, a bartender just nodded knowingly.",
  "This is why we drink. Well, one of the reasons.",
  "And with that, we're emotionally ordering another round.",
  "The only appropriate response is to order a flight and try all four.",
  "We're going to need a bigger cooler for this one.",
  "Cheers to the beautiful absurdity of sports.",
  "That's the kind of play that sells pints.",
  "We paused to take a sip. We suggest you do the same.",
  "If that doesn't call for a celebratory chug, nothing does.",
  "Quick beer break. Okay, we're back.",
  "The beer tastes better when your team is winning. Science.",
  "We'd pour one out, but that's alcohol abuse. We'll drink it instead.",
  "A toast: to whoever bet the over on this one.",
  "This game pairs well with an amber ale and low expectations.",
  "Let's move on before we need another pitcher.",
  "And just like that, the mood at the bar shifts.",
  "Time for a palate cleanser — and by that, we mean another beer.",
  "The fridge isn't going to empty itself. Unlike this team's chances.",
  "We'll drink to sportsmanship. We'll drink to everything, really.",
  "That play was smoother than a fresh pour on nitro.",
  "Grab a refill — the second half promises to be a doozy.",
  "Speaking of things that go down smooth...",
  "And the crowd goes wild. And the beer goes down easy.",
  "Someone cue the highlight reel and the drink specials.",
  "We interrupt this recap for a sponsored beer moment. Just kidding. Mostly.",
  "Back from the beer run. What'd we miss? Everything? Cool.",
  "That's enough drama to warrant a whole pitcher.",
  "The only stat that matters right now is our blood alcohol content.",
  "Hold that thought — and hold our beer.",
  "What a time to be alive and slightly buzzed.",
  "This calls for the good stuff. Not the light beer. The real stuff.",
  "We've seen bar fights less intense than this game.",
  "And on that bombshell, let's hydrate. With beer.",
  "That's going in the highlight reel and our drinking stories.",
  "Every sip of our beer tasted like victory watching that play.",
  "The pub quiz about this game is going to be legendary.",
  "We'd explain the strategy but we're three deep and it's complicated.",
  "In the time it took to read that paragraph, we finished a beer.",
  "That sequence deserves its own beer named after it.",
  "Somebody ring the bell — last call for the losing team's hopes.",
  "Like a proper stout, this game has layers.",
  "Moving right along, much like the beer through our system.",
  "The only thing flowing faster than the goals is the draft.",
  "And that, friends, is what we in the business call 'a moment.'",
];

// ─── Humor Interjections (55 entries) ───────────────────────────────────────

export const humorInterjections: string[] = [
  "And yes, we checked — that score is real.",
  "No, your eyes aren't deceiving you.",
  "We wish we were making this up.",
  "You can't script this stuff. Seriously, Hollywood would reject it.",
  "(Narrator: It was, in fact, that bad.)",
  "We'll give you a moment to process that.",
  "Read that again. Slowly.",
  "Let that sink in. We'll wait.",
  "For the record, we triple-checked.",
  "Yes, that actually happened. In a professional sport. On purpose.",
  "And no, this isn't satire. Though we understand the confusion.",
  "Believe it or not, this gets weirder.",
  "We're not crying, you're crying. Okay, we're both crying.",
  "Sports, everybody. Sports.",
  "Somewhere, a sports analyst just spit out their coffee.",
  "The spreadsheet nerds are having a field day with this one.",
  "Analytics Twitter is going to explode.",
  "Your fantasy team owners are either thrilled or devastated. No in-between.",
  "There is no in-between with this team.",
  "At this point, we're just along for the ride.",
  "The audacity. The absolute audacity.",
  "Chef's kiss. No notes.",
  "If you turned this game off early, we have bad news about your decision-making.",
  "This is fine. Everything is fine. (It is not fine.)",
  "We'd make a joke, but reality already did that for us.",
  "The memes are writing themselves at this point.",
  "Even the commentators ran out of words for that one.",
  "File this under: Things We Didn't See Coming.",
  "That's going straight to the blooper reel.",
  "Plot twist nobody asked for but everyone deserved.",
  "Okay, but seriously — how?",
  "In today's edition of 'Sports Are Weird'...",
  "We genuinely don't know how to feel about this.",
  "Somebody tell us this is a simulation.",
  "The stat sheet doesn't lie. We kind of wish it did.",
  "Well, that happened. Moving on.",
  "Is it too early to call this game of the year? Asking for a friend.",
  "We've been staring at this box score for five minutes.",
  "That's the kind of stat line that ruins friendships.",
  "The record books just got a new entry.",
  "Alexa, play the sad trombone.",
  "The commentator literally said 'wow' three times. Same.",
  "We've officially entered the 'anything can happen' zone.",
  "If you had this on your bingo card, you're a wizard.",
  "Statistically improbable. Actually happened anyway.",
  "The laws of physics would like a word.",
  "Our collective jaws are on the floor.",
  "That's not even fair. Like, actually unfair.",
  "We need a moment. Or twelve.",
  "This is the kind of game that makes you question everything.",
  "If this were a movie, you'd say it was unrealistic.",
  "The scoreboard operator just looked at the camera like they were on The Office.",
  "Let's all just take a breath here.",
  "We've seen it all now. Actually, no, sports will surprise us again tomorrow.",
  "The universe has a sense of humor, and today it's laughing at us.",
];

// ─── Opening Lines (35 entries) ─────────────────────────────────────────────

export const openingLines: string[] = [
  'Well, sports fans, grab your beverage of choice because this one is a doozy.',
  "In what can only be described as a 'hold my beer' moment...",
  'Settle in, crack a cold one, and prepare yourself for this.',
  'Good evening, you beautiful degenerates. We have sports to discuss.',
  "If you haven't already poured yourself something, now's the time.",
  "Oh boy. Where do we even begin with this one?",
  "Buckle up, buttercup — this game was something else.",
  "Ladies, gentlemen, and fellow couch warriors — we bring news.",
  "Stop what you're doing. Put down everything except your drink.",
  "What a day. What a beautiful, chaotic, beer-worthy day in sports.",
  "You know those games you tell your grandkids about? This is one.",
  "Grab a seat. Grab a beer. This is going to be good.",
  "We interrupt your regularly scheduled scrolling for something actually interesting.",
  "In news that has us reaching for the top shelf...",
  "Another day, another reason to love (and question) sports.",
  "If sports were a bar, today's menu would be 100% chaos on draft.",
  "Friends, we gather here today to discuss what just happened in sports.",
  "The sports gods have spoken, and they have chosen violence.",
  "Pull up a barstool — you're going to want to sit down for this.",
  "Welcome back to the only sports coverage that pairs with a cold one.",
  "Some games are forgettable. This was not one of them.",
  "Today in sports: drama, heartbreak, and the occasional moment of actual competence.",
  "We've got a fresh one for you today, and it's better served cold.",
  "Clear your schedule and fill your glass — this is a big one.",
  "It's a great day to be a sports fan and a better day to be a beer fan.",
  "Breaking out the good glasses for this recap. This game deserves it.",
  "There are normal games. And then there's whatever this was.",
  "Sports happened today. And they happened HARD.",
  "Alert: This recap contains scenes of athletic excellence and poor refereeing.",
  "Today's sports forecast: 100% chance of overreactions and cold beverages.",
  "Let us set the scene: a packed stadium, two teams, and zero chill.",
  "The scoreboard don't lie, and today it's telling quite a story.",
  "Before we get into this, we need you to promise you're sitting down.",
  "Another absolute banger of a game and we are HERE for it.",
  "Wake up, sports fans. We've got something brewing — and we don't just mean the coffee.",
];

// ─── Closing Lines (35 entries) ─────────────────────────────────────────────

export const closingLines: string[] = [
  "And on that note, we're heading to the bar. Cheers.",
  "That's all from us. Tip your bartender.",
  "Until next time — stay hydrated. With beer.",
  "That's a wrap. We'll be at the pub if you need us.",
  "Game over. Beer o'clock has officially begun.",
  "The final buzzer has sounded, and so has our liver's alarm.",
  "And that, dear readers, is why we watch sports. And drink beer.",
  "We're off to toast this absolute spectacle of a game.",
  "The bar's calling. We'll see you at the next one.",
  "Last call for hot takes. First call for cold beers.",
  "Thanks for joining us. Your tab is still open.",
  "That's the final whistle on this recap. Somebody pour us something.",
  "And we're out. Like the losing team's playoff hopes.",
  "Stay thirsty, friends. Both for sports and for beverages.",
  "This has been your beer-soaked sports update. You're welcome.",
  "We'd keep going, but our pint glass is empty. Priorities.",
  "Signing off with a full heart and an empty glass.",
  "That's all, folks. The fridge awaits.",
  "End of game. Beginning of happy hour.",
  "We hope you enjoyed this as much as we enjoyed writing it slightly buzzed.",
  "And that's the ball game. Now someone pass us a drink.",
  "Until the next disaster/masterpiece, keep those coolers stocked.",
  "Time to close this tab — both the browser and the bar one.",
  "Final thoughts: wow. That's it. That's the thought. Wow.",
  "If you made it this far, you deserve a beer. On us. (Not really. We're a website.)",
  "That's it from the best seats in the house — our couches.",
  "We're gonna need a bigger recap. And a bigger beer.",
  "Thanks for reading. We're going to go stare at the wall and process this game.",
  "And with that, the only thing left to do is cheers. So cheers.",
  "Closing time — you don't have to go home, but you can't stay here.",
  "The game is over, the recap is done, and our sobriety is questionable.",
  "Raise your glass to another day of sports. Lower your expectations for tomorrow.",
  "That does it for us. May your teams win and your beers be cold.",
  "On that note, we're tapping out. Catch you on the flip side.",
  "And scene. Somebody hit the lights and open the taps.",
];

// ─── Sentiment Phrases ──────────────────────────────────────────────────────

export const sentimentPhrases = {
  bigWin: [
    'Absolutely dominant.',
    'That was a statement game.',
    'Total control from start to finish.',
    'This team means business.',
    'A performance for the ages.',
    'Put that one in a frame.',
    "They didn't just win — they made a point.",
    "That's the kind of win that echoes.",
    'Championship-caliber performance right there.',
    'Complete and utter destruction.',
  ],
  closeWin: [
    'Survived by the skin of their teeth.',
    "Ugly? Yes. A win? Also yes. We'll take it.",
    'A win is a win, even if it took ten years off our lives.',
    "Not pretty, but effective. Like most of us at last call.",
    "Gritty, gutsy, and they'll take it.",
    "That's called clutch. Or luck. Probably both.",
    'Pulled it out when it mattered most.',
    'They found a way. Barely.',
    "Heart attack football at its finest.",
    "The ugly wins count the same on the standings.",
  ],
  loss: [
    "Rough night. The less said, the better.",
    "That one's going to sting for a while.",
    "Back to the drawing board.",
    "They'll want to forget this one. We won't let them.",
    "A performance that inspires drinking.",
    "The only silver lining is that it's over.",
    "If you're a fan of this team, our condolences.",
    "That was... something. Not something good, but something.",
    "They showed up, technically. That's about all we can say.",
    "Time heals all wounds. Beer helps in the meantime.",
  ],
  upset: [
    'Nobody saw this coming!',
    'The underdog has bitten back.',
    "Alert: chaos has entered the chat.",
    "Tear up your brackets. Burn your predictions. Start over.",
    "The sports gods love nothing more than an upset.",
    "David just knocked out Goliath, and the crowd is going mental.",
    "If you bet on this, you're either psychic or insane. Congrats.",
    "The favorites? Humbled. The underdogs? Legendary.",
    "This is why they play the games, folks.",
    "Form goes out the window. Magic walks in.",
  ],
  controversy: [
    "The refs are catching heat, and honestly, they kind of deserve it.",
    "VAR/Review just became the most hated technology since the alarm clock.",
    "That call is going to be debated in bars for decades.",
    "Controversial doesn't even begin to cover it.",
    "Twitter is a warzone over this one.",
    "We're not going to weigh in on the call. Just kidding — it was awful.",
    "The officiating tonight could generously be described as 'creative.'",
    "That decision will haunt the league office for weeks.",
    "Hot take: the refs need glasses. Cold take: everyone agrees.",
    "If bad calls were beers, the refs would be running a microbrewery.",
  ],
} as const;

// ─── Utility ────────────────────────────────────────────────────────────────

/**
 * Pick a random phrase from an array.
 */
export function randomPhrase(phrases: readonly string[]): string {
  return phrases[Math.floor(Math.random() * phrases.length)]!;
}

/**
 * Pick N unique random phrases from an array.
 */
export function randomPhrases(phrases: readonly string[], count: number): string[] {
  const shuffled = [...phrases].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
